export * from './content';
export * from './components/Header';
export * from './components/HeroSection';
export * from './components/ScreenshotsSection';
export * from './components/AdvantagesSection';
export * from './components/ProcessSection';
export * from './components/EFCSection';
export * from './components/SuccessStoriesSection';
export * from './components/FooterSection';
